<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.dug22</groupId>
    <artifactId>CipherLabs</artifactId>
    <version>1.0.1</version>
    <packaging>pom</packaging>
    <name>CipherLabs</name>

    <modules>

        <module>cipher-labs-core</module>
        <module>cipher-labs-lockspot</module>
        <module>cipher-labs-app</module>
        <module>cipher-labs-resources</module>
        <module>cipher-labs-ui</module>
    </modules>

</project>